### ISSUE TITLE
How to prevent Memory Percentage increase over time?

### ISSUE THREAD

**Issue by gotbletu** [sachaos/viddy#38]
hey i notice that if i leave viddy running for a few hours, the memory % would increase. Is there a way to prevent this?
_**viddy**_ starts out at 0.1% after a few hours it would be over 4.0%.
the **_watch_** command is always at 0.0% even after a few hours.

Not sure if is due to the viddy time machine feature that records all the changes but if so, maybe add an option to disable it to prevent memory % increase.

```
# example
viddy -t man ffmpeg
viddy -t "ps -o pid,user,%mem,command ax | sort -b -k3 -r | grep -i viddy"
```

----
viddy 0.3.4-1
System:    Host: arcolinux Kernel: 5.10.83-1-lts x86_64 bits: 64 Desktop: Xfce 4.16.0 Distro: ArcoLinux

**Comment by onedr0p** [comment]
Hitting spacebar while in viddy hides the time machine feature, maybe that also disables it? Have you tried?

**Comment by kjk11** [comment]
Same problem here, great application, but the memory usage slowly keeps going up until the system runs out of RAM.

**Comment by onedr0p** [comment]
It's probably worth setting like a 100 history limit by default but maybe make it configurable @sachaos ?

**Comment by sachaos** [comment]
I'll try to solve this issue in this weekend.

**Comment by paulie-g** [comment]
I see that this feature branch was never merged into master. I would respectfully suggest that you do so, and cut a release. A lot of people use watch/viddy for long-running monitoring. The time machine functionality is neat, but not at the expense of unbounded memory consumption.

**Comment by dylan-tock** [comment]
> I see that this feature branch was never merged into master. I would respectfully suggest that you do so, and cut a release. A lot of people use watch/viddy for long-running monitoring. The time machine functionality is neat, but not at the expense of unbounded memory consumption.

Just had a box get into a state that required a total restart because of this.

**Comment by onedr0p** [comment]
Any update @sachaos ?

**Comment by sachaos** [comment]
@onedr0p Hi thank you for ping.

I think there are many solutions.

1. limit snapshot count.
2. store history in file.
    - SQLite ? https://github.com/sachaos/viddy/issues/104
3. Remove 0 diff snapshot.
    - I've merged https://github.com/sachaos/viddy/pull/99

**Comment by fedorkanin** [comment]
I use viddy for git log monitoring on MacOS, this is the command I use:

```bash
viddy --interval 1s --no-title --skip-empty-diffs 'GIT_PAGER=cat git log --all --oneline --graph --decorate --color'
```

The issue with unbounded and increasing memory consumption (after a day or so it can be more than **several gigabytes**) in my case is not solved with `--skip-empty-diffs`. I do not really understand what is taking up so much memory and would be happy to cooperate by providing logs if requested.

As for my workflow, an ideal solution would be to limit the snapshot count, either via a flag or a global configuration.

**Comment by sachaos** [comment]
I've implemented feature to save and load history.
We have been storing results in memory until now, but since we switched to using SQLite, we expect a significant reduction in memory usage. If you encounter any bugs or issues, please let us know.

https://github.com/sachaos/viddy/issues/117#issuecomment-2294818886

**Comment by paulie-g** [comment]
> I've implemented feature to save and load history in viddy v1.0.0-rc.2. We have been storing results in memory until now, but since we switched to using SQLite, we expect a significant reduction in memory usage. If you encounter any bugs or issues, please let us know.

I can't speak for absolutely everyone, but the people in this thread who knew what they wanted asked for an ability to put an upper bound on in-memory storage. This is because their data is ephemeral and not worth hammering flash, ie they are using viddy as a drop-in replacement for, say, watch. Saving data to SQLite is - at best - orthogonal and, unless you're using an in-memory table, potentially even more unsuitable to their use case.

**Comment by sachaos** [comment]
@paulie-g Oh, you're right. I apologize for the misunderstanding.
Yes, the SQLite backend won't resolve this issue.
We'll need to limit the history length.

Thank you!

**Comment by lcnbr** [comment]
I am getting ` 0: database or disk is full` error now. Where is the database file stored?

**Comment by onedr0p** [comment]
I'm curious with the rust rewrite, is this issue still relevant?

@lcnbr maybe open a new issue or look thru the code to see where it is?
